USE example_db;

SET NAMES utf8mb4;

START TRANSACTION;

-- -- Data registration in the examples table
-- INSERT INTO examples VALUES (NULL, 'example_name1');
-- INSERT INTO examples VALUES (NULL, 'example_name2');
-- INSERT INTO examples VALUES (NULL, '日本語テスト');

INSERT INTO vEvent VALUES (1, 'ucdId0001', 'mediaId0001');
INSERT INTO vEvent VALUES (2, 'ucdId0001', 'mediaId0002');
INSERT INTO vEvent VALUES (3, 'ucdId0001', 'mediaId0003');
INSERT INTO vEvent VALUES (4, 'ucdId0001', 'mediaId0004');

INSERT INTO rRule VALUES (
  1, -- rRuleId int not null AUTO_INCREMENT,
  1, -- vEventId int not null,
  '2022-09-01 00:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 00:10:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-03 00:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  2, -- rRuleId int not null AUTO_INCREMENT,
  2, -- vEventId int not null,
  '2022-09-01 00:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 00:20:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-04 00:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  3, -- rRuleId int not null AUTO_INCREMENT,
  3, -- vEventId int not null,
  '2022-09-01 00:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 00:30:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-05 00:30:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  4, -- rRuleId int not null AUTO_INCREMENT,
  4, -- vEventId int not null,
  '2022-09-01 00:30:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 00:40:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-11 00:40:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  5, -- rRuleId int not null AUTO_INCREMENT,
  5, -- vEventId int not null,
  '2022-09-01 00:50:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 01:00:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-12 01:00:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  6, -- rRuleId int not null AUTO_INCREMENT,
  6, -- vEventId int not null,
  '2022-09-01 01:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 01:10:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  7, -- rRuleId int not null AUTO_INCREMENT,
  7, -- vEventId int not null,
  '2022-09-05 01:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-05 01:20:00',-- dtEnd DATETIME,
  'single', -- freq varchar(8),
  '2022-09-05 01:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  8, -- rRuleId int not null AUTO_INCREMENT,
  8, -- vEventId int not null,
  '2022-09-05 01:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-05 01:30:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-11 01:30:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  9, -- rRuleId int not null AUTO_INCREMENT,
  9, -- vEventId int not null,
  '2022-09-06 01:30:00', -- dtStart DATETIME NOT NULL,
  '2022-09-06 01:40:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-10 01:40:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  10, -- rRuleId int not null AUTO_INCREMENT,
  10, -- vEventId int not null,
  '2022-09-11 01:40:00', -- dtStart DATETIME NOT NULL,
  '2022-09-11 01:50:00',-- dtEnd DATETIME,
  'single', -- freq varchar(8),
  '2022-09-11 01:50:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  11, -- rRuleId int not null AUTO_INCREMENT,
  11, -- vEventId int not null,
  '2022-09-11 01:50:00', -- dtStart DATETIME NOT NULL,
  '2022-09-11 02:00:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  12, -- rRuleId int not null AUTO_INCREMENT,
  12, -- vEventId int not null,
  '2022-09-05 02:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-05 02:10:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  13, -- rRuleId int not null AUTO_INCREMENT,
  13, -- vEventId int not null,
  '2022-09-04 02:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 02:20:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  14, -- rRuleId int not null AUTO_INCREMENT,
  14, -- vEventId int not null,
  '2022-09-12 02:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-12 02:30:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  15, -- rRuleId int not null AUTO_INCREMENT,
  15, -- vEventId int not null,
  '2022-09-12 02:30:00', -- dtStart DATETIME NOT NULL,
  '2022-09-12 02:40:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  '2022-09-13 02:40:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  16, -- rRuleId int not null AUTO_INCREMENT,
  16, -- vEventId int not null,
  '2022-09-13 02:40:00', -- dtStart DATETIME NOT NULL,
  '2022-09-13 02:50:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  17, -- rRuleId int not null AUTO_INCREMENT,
  17, -- vEventId int not null,
  '2022-09-13 02:50:00', -- dtStart DATETIME NOT NULL,
  '2022-09-13 03:00:00',-- dtEnd DATETIME,
  'single', -- freq varchar(8),
  '2022-09-13 03:00:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  18, -- rRuleId int not null AUTO_INCREMENT,
  18, -- vEventId int not null,
  '2022-08-29 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-08-29 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-12 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'mo', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  19, -- rRuleId int not null AUTO_INCREMENT,
  19, -- vEventId int not null,
  '2022-08-29 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-08-29 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'mo', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  20, -- rRuleId int not null AUTO_INCREMENT,
  20, -- vEventId int not null,
  '2022-08-30 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-08-30 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-13 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'tu', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  21, -- rRuleId int not null AUTO_INCREMENT,
  21, -- vEventId int not null,
  '2022-08-30 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-08-30 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'tu', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  22, -- rRuleId int not null AUTO_INCREMENT,
  22, -- vEventId int not null,
  '2022-08-31 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-08-31 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-14 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'we', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  23, -- rRuleId int not null AUTO_INCREMENT,
  23, -- vEventId int not null,
  '2022-08-31 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-08-31 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'we', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  24, -- rRuleId int not null AUTO_INCREMENT,
  24, -- vEventId int not null,
  '2022-09-01 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-15 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'th', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  25, -- rRuleId int not null AUTO_INCREMENT,
  25, -- vEventId int not null,
  '2022-09-01 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'th', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  26, -- rRuleId int not null AUTO_INCREMENT,
  26, -- vEventId int not null,
  '2022-09-02 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-02 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-16 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'fr', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  27, -- rRuleId int not null AUTO_INCREMENT,
  27, -- vEventId int not null,
  '2022-09-02 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-02 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'fr', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  28, -- rRuleId int not null AUTO_INCREMENT,
  28, -- vEventId int not null,
  '2022-09-03 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-03 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-17 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'sa', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  29, -- rRuleId int not null AUTO_INCREMENT,
  29, -- vEventId int not null,
  '2022-09-03 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-03 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'sa', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  30, -- rRuleId int not null AUTO_INCREMENT,
  30, -- vEventId int not null,
  '2022-09-04 03:00:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 03:10:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-18 03:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'su', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  31, -- rRuleId int not null AUTO_INCREMENT,
  31, -- vEventId int not null,
  '2022-09-04 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'su', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  32, -- rRuleId int not null AUTO_INCREMENT,
  32, -- vEventId int not null,
  '2022-08-29 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-08-29 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-12 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'mo,tu', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  33, -- rRuleId int not null AUTO_INCREMENT,
  33, -- vEventId int not null,
  '2022-08-29 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-08-29 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'mo,tu', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  34, -- rRuleId int not null AUTO_INCREMENT,
  34, -- vEventId int not null,
  '2022-08-30 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-08-30 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-13 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'tu,we', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  35, -- rRuleId int not null AUTO_INCREMENT,
  35, -- vEventId int not null,
  '2022-08-30 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-08-30 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'tu,we', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  36, -- rRuleId int not null AUTO_INCREMENT,
  36, -- vEventId int not null,
  '2022-08-31 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-08-31 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-14 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'we,th', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  37, -- rRuleId int not null AUTO_INCREMENT,
  37, -- vEventId int not null,
  '2022-08-31 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-08-31 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'we,th', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  38, -- rRuleId int not null AUTO_INCREMENT,
  38, -- vEventId int not null,
  '2022-09-01 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-15 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'th,fr', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  39, -- rRuleId int not null AUTO_INCREMENT,
  39, -- vEventId int not null,
  '2022-09-01 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-01 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'th,fr', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  40, -- rRuleId int not null AUTO_INCREMENT,
  40, -- vEventId int not null,
  '2022-09-02 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-02 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-16 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'fr,sa', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  41, -- rRuleId int not null AUTO_INCREMENT,
  41, -- vEventId int not null,
  '2022-09-02 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-02 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'fr,sa', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  42, -- rRuleId int not null AUTO_INCREMENT,
  42, -- vEventId int not null,
  '2022-09-03 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-03 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-17 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'sa,su', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  43, -- rRuleId int not null AUTO_INCREMENT,
  43, -- vEventId int not null,
  '2022-09-03 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-03 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'sa,su', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  44, -- rRuleId int not null AUTO_INCREMENT,
  44, -- vEventId int not null,
  '2022-09-04 03:10:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 03:20:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  '2022-09-18 03:20:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'su,mo', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  45, -- rRuleId int not null AUTO_INCREMENT,
  45, -- vEventId int not null,
  '2022-09-04 03:20:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 03:30:00',-- dtEnd DATETIME,
  'weekly', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  'su,mo', -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  46, -- rRuleId int not null AUTO_INCREMENT,
  46, -- vEventId int not null,
  '2022-09-04 23:50:00', -- dtStart DATETIME NOT NULL,
  '2022-09-05 00:10:00',-- dtEnd DATETIME,
  'single', -- freq varchar(8),
  '2022-09-05 00:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  47, -- rRuleId int not null AUTO_INCREMENT,
  47, -- vEventId int not null,
  '2022-09-11 23:50:00', -- dtStart DATETIME NOT NULL,
  '2022-09-12 00:10:00',-- dtEnd DATETIME,
  'single', -- freq varchar(8),
  '2022-09-12 00:10:00', -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  48, -- rRuleId int not null AUTO_INCREMENT,
  48, -- vEventId int not null,
  '2022-09-04 03:30:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 03:40:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);

INSERT INTO rRule VALUES (
  49, -- rRuleId int not null AUTO_INCREMENT,
  49, -- vEventId int not null,
  '2022-09-04 03:50:00', -- dtStart DATETIME NOT NULL,
  '2022-09-04 04:00:00',-- dtEnd DATETIME,
  'daily', -- freq varchar(8),
  NULL, -- until DATETIME,
  NULL, -- cnt int,
--  NULL, -- interval int default 1,
  NULL, -- bySecond varchar(170),
  NULL, -- byMinute varchar(170),
  NULL, -- byHour varchar(61),
  NULL, -- byDay varchar(35),
  NULL, -- byMonthDay varchar(200),
  NULL, -- byYearDay varchar(3078),
  NULL, -- byWeekNo varchar(353),
  NULL, -- byMonth varchar(29),
  NULL, -- wkSt char(2) default 'mo',
  NOW(), -- created DATETIME,
  NOW()  -- updated DATETIME,
);





INSERT INTO exDate VALUES (
  1, -- exDate int not null AUTO_INCREMENT,
  48, -- rRuleId int not null,
  '2022-09-05 00:00:00', -- dt DATETIME NOT NULL,
  NOW(), -- created DATETIME,
  NOW() -- updated DATETIME,
);



INSERT INTO recurrence VALUES (
  1, -- recurrenceId int not null AUTO_INCREMENT,
  49, -- rRuleId int not null,
  '2022-09-06 23:40:00', -- dtStart DATETIME NOT NULL,
  '2022-09-06 03:50:00',-- dtEnd DATETIME,
  NOW(), -- created DATETIME,
  NOW() -- updated DATETIME,
);

COMMIT;